/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: RED2000 (https://sketchfab.com/RED2000)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/baseball-bat-ab9a636bd1ed4b3188062c072f93fa09
Title: Baseball Bat
*/
"use client"
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { dispose, useFrame } from '@react-three/fiber'

export default function BaseballBat(props) {
  const { nodes, materials } = useGLTF('/models/baseball_bat.glb')
  const modelRef = useRef()
  useFrame( () => {
    modelRef.current.rotation.y += 0.015
  })

  return (
    <group 
      {...props} 
      dispose={null} 
      scale={[0.20, 0.20, 0.20]}
      position={[0, -2, 0]}
      ref={modelRef}
    >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_2.geometry}
        material={materials.initialShadingGroup}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload('/models/baseball_bat.glb')