// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// Author: butterstotch (https://sketchfab.com/butterstotch)
// License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
// Source: https://sketchfab.com/3d-models/baseball-cap-ny-b7ecae3e46554ef4ab0b43ee97106e04
// Title: Baseball Cap NY
// */

// "use client"

// import React, { useRef } from 'react'
// import { useGLTF } from '@react-three/drei'
// import { useFrame } from '@react-three/fiber'

// export default function Hat(props) {
//   const { nodes, materials } = useGLTF('/models/baseball_cap_ny.glb')

//   const modelRef = useRef()
//   useFrame( () => {
//     console.log("model.current:::", modelRef.current)
//     modelRef.current.rotation.y += 0.015
    
//   })

  

//   return (
//     <group 
//       {...props} 
//       dispose={null} 
//       ref={modelRef} 
//       scale={[1.8, 1.8, 1.8]}
//       rotation={[0.4, -1, 0]}
//       position={[0, 0, 0]}
//     >
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Object_2.geometry}
//         material={materials.initialShadingGroup}
//         position={[0, -3.867, 0]}
//         rotation={[-Math.PI / 2, 0, 0]}
//         // scale={[-1, 1, 1]}
//       />
//     </group>
//   )
// }

// useGLTF.preload('/models/baseball_cap_ny.glb')


"use client";

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export default function Hat(props) {
  const { nodes, materials } = useGLTF("/models/baseball_cap_ny.glb");

  const modelRef = useRef();

  useFrame(() => {
    if (modelRef.current) {
      modelRef.current.rotation.y += 0.015; // Apply rotation
    } else {
      console.warn("modelRef.current is null");
    }
  });

  // return (
  //   <group
  //     {...props}
  //     dispose={null}
  //     ref={modelRef} // Assign ref to the group
  //     scale={[1.8, 1.8, 1.8]}
  //     rotation={[0.4, -1, 0]}
  //     position={[0, 0, 0]}
  //   >
  //     <mesh
  //       castShadow
  //       receiveShadow
  //       geometry={nodes.Object_4.geometry} // Ensure correct node
  //       material={materials.initialShadingGroup} // Ensure correct material
  //       position={[0, -3.867, 0]}
  //       rotation={[-Math.PI / 2, 0, 0]}
  //     />
  //   </group>
  // );
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials['Material.004']}
        position={[0.001, -0.797, -0.016]}
        rotation={[0.013, 0, -Math.PI]}
        scale={[-1, 1, 1]}
      />
    </group>
  )
}

useGLTF.preload("/models/baseball_cap_ny.glb");
